name: Shells commands in Github actions

on: [push]


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello world"
      - name: Multipline script
        run: |
          node -v
          npm -v