name: Shells commands in Github actions

on: [push]


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: Multipline script
        run: |
          node -v
          npm -v
      - name: python command
        run : |
          import platform
          print(platform.processor())
        shell: python